name: Percona CVE Actions
on: workflow_dispatch
jobs:
  tags-generation:
    name: Generating versions list
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
      - name: Get data from docker hub and set matrix
        id: setmatrix
        run: |
           content=`curl "https://hub.docker.com/v2/repositories/library/percona/tags/?page_size=5&name&ordering"`
           #echo "::set-output name=matrix::$content";
           #results=`echo $content | jq -j ".results"`
           #echo $results
           results='[{name: "hello"}, {name: "213"}]'
           echo $results
           echo "::set-output name=matrix::$results"
  trivy-testing:
    name: Testing repositries on Trivy
    needs: tags-generation
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.tags-generation.outputs.matrix).results}}
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'percona:${{ matrix.name }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
